### ISSUE TITLE
Archive Retrieval Funcs list \

### ISSUE THREAD

**Issue by jibalio** [lerycibalio/msa-mis#14]
# Archiver.cs Public Methods
## Assignments
_public static DataTable_ **GetAssignmentHistory** (int GID)
Returns archive guard's list of previous assignments.
`cols` 

## Duty Details & Attendance
_public static DataTable_ **GetDutyDetailsSummary** (int AID)
Returns the duty details of a guard's specific assignment.
`cols: DID, TimeIn, TimeOut, Days`
<hr />

 _public static DataTable_ **GetPeriods** (int GID)
Returns a list of periods wheere guard was active. 
Para ni sa attendance ug sa payroll na combobox
`cols: month, period, year`
![](http://i.imgur.com/8DzLpyG.png)
<hr />

_public static DataTable_ **GetAttendance** (int GID, int month, int period, int year)
Returns attendance details of guard on a specific yyyy/MM/period.
`cols: atid, did, date, day, schedule, timein, timeout`

## Payroll
 _public static Payroll_ **GetPayroll** (int GID, int month, int period, int year)
Returns payroll object. Sa payroll gui, instead of constructing a payroll object, diretso na i assign ang _pay object sa return type of this method.
```
if (ArchiveFlag) 
    then _pay = Archiver.GetPayroll (gid, month, period, year)
```

**Comment by AJPasigado** [comment]
Bes, pa-add ko please
Archiver.GetAttendanceSummary()
Archiver.GetAssignmentDetails(Aid)
Archiver.GetAllAssignmentDetails(Aid)

Payroll is done

**Comment by jibalio** [comment]
_public static DataTable_ **GetAssignmentDetails** (int aid)
`cols: location, contractstart, contractend`

_public static DataTable_ **GetAllAssignmentDetails** (int AID)
`cols: gid, cid, guardname, clientname, status`
