### ISSUE TITLE
Rates GUI & Default values for Bonuses

### ISSUE THREAD

**Issue by jibalio** [lerycibalio/msa-mis#3]
# Rates GUI

![](http://i.imgur.com/Hrt1a31.png)

- [x] Make fields lng for these rate multipliers
- [x] How do I get rates_id?
`static DataTable Payroll.GetRatesList()`
- [x] Getters for rates
- [x] aj use given getters below:

# Default Bonus Values GUI

- [x] **Create GUI**
- [x] Feed to `static Payroll.SetBonusDefaults(philhealth, pagibig, cashbond, cola, emergencyallowance)`
in double
- [x] Connect setters

**Comment by AJPasigado** [comment]
Bes need nako getter for Default Rates

**Comment by AJPasigado** [comment]
Getter for Rates GUI

order by clause in GetRatesList() pls
