### ISSUE TITLE
Frontend: Connect Payroll Adjustment GUI to Payroll.cs

### ISSUE THREAD

**Issue by jibalio** [lerycibalio/msa-mis#4]
# Frontend: Connect Payroll Adjustment GUI to Payroll.cs
@AJPasigado 
![](http://i.imgur.com/XcBr2vX.png)

## How?
Simply assign to fields. Sample:
```
pay.CashAdvance = 99.99
pay.Cola = 103.27
pay.EmergencyAllowance = 2500.00
pay.CashBond = 50.00
pay.CashAdvance = 1000.00
```
Then i-detect lng na niya na nag change, tapos update agad sa db.

**Important:** Only re-assign what was changed. Kay mag log na sya for every change (trigger). To save processing time pd (query).

**Comment by AJPasigado** [comment]
Tapos na pooo...
