### ISSUE TITLE
Broken Stuff/Bugs

### ISSUE THREAD

**Issue by jibalio** [lerycibalio/msa-mis#9]
## Main Database
- [x] 10.00 input for multipliers
- [x] Adding Unassignment Request

## Archive Related
- [x] No Contract End on SDutyAssignment

**Comment by AJPasigado** [comment]
bes walay ga ani sa akoa, which guard to?

**Comment by lerycibalio** [comment]
@AJPasigado sa tanan sya sa akoa... idk check nako
